### ISSUE TITLE
Ubuntu 15.10

### ISSUE THREAD

**Issue by conradjones** [plivo/sharq-server#3]
Ubuntu 15.10

```
  ___ _              ___    ___
 / __| |_  __ _ _ _ / _ \  / __| ___ _ ___ _____ _ _
 \__ \ ' \/ _` | '_| (_) | \__ \/ -_) '_\ V / -_) '_|
 |___/_||_\__,_|_|  \__\_\ |___/\___|_|  \_/\___|_|

Version: 0.2.0

Listening on: 127.0.0.1:8080
```

Error: class uri 'gevent' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 139, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 24, in <module>
    from gevent.server import StreamServer
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 6, in <module>
    from gevent.socket import EWOULDBLOCK, socket
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

**Comment by conradjones** [comment]
runs fine in ubuntu 14.04
